### ISSUE TITLE
Does not compile anymore (ppport.h missing)

### ISSUE THREAD

**Issue by eserte** [PDLPorters/PDL-Parallel-threads#1]
See http://matrix.cpantesters.org/?dist=PDL-Parallel-threads%200.03;reports=1#sl=7,1 for a cpantesters report overview --- there are no successful compiles since some months here. Looking at one of the reports I see:

```
cc -I"/bbbike/perl-5.20.2/lib/site_perl/5.20.2/x86_64-linux/PDL/Core" -I/opt/perl-5.20.2/lib/5.20.2/x86_64-linux/CORE -DXS_VERSION="0.03" -DVERSION="0.03" -fPIC -c -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -o lib/PDL/Parallel/threads.o lib/PDL/Parallel/threads.c
lib/PDL/Parallel/threads.xs:4:20: fatal error: ppport.h: No such file or directory
compilation terminated.
```

This is on my smoker machine and I can confirm that ppport.h exists here:

```
$ ls -al /bbbike/perl-5.20.2/lib/site_perl/5.20.2/x86_64-linux/PDL/Core/ppport.h 
-r--r--r-- 1 root root 156706 May 12  2013 /bbbike/perl-5.20.2/lib/site_perl/5.20.2/x86_64-linux/PDL/Core/ppport.h
```

However it's possible that the double quotes in the `-I` option are used _literally_, so the C compiler cannot find the header file.

**Comment by abensonca** [comment]
The double quotes do seem to be the problem. Modifying Build.PL to strip them allows it to build successfully:

`my $inc = PDL_INCLUDE;
$inc =~ s/-I//g;
$inc =~ s/"//g;`

**Comment by hadjiprocopis** [comment]
I can confirm that  abensonca's solution works.

**Comment by run4flat** [comment]
First, sorry it's taken so long to get this fixed. My Perl work goes in seasons, and the emails for this dropped off my screen and I never realized what was going on. Sorry for the long-lived bug.

Second, hey, people are using my module! Holy cow, I never thought anybody paid any attention to it. Now that I know it's used by stuff I'll try to be a bit more responsive!

Third and finally, thank you for the solution @abensonca. I worry that this might cause things to break on Windows, but I'll let CPAN Testers smoke that out for me.

**Comment by mohawk2** [comment]
This is because your Module::Build script is naively passing what PDL gives it directly to the executable, but PDL (being EUMM-orientated) protects things from the shell. The more idiomatic way here would be to use `shellwords` on the return from `PDL_INCLUDE`:

```perl
use Text::ParseWords qw(shellwords);
# ...
include_dirs => [map {(my $f = $_) =~ s/^-I//; $f} shellwords PDL_INCLUDE],
```
