### ISSUE TITLE
Slowdown in this module with PDL 2.076

### ISSUE THREAD

**Issue by mohawk2** [PDLPorters/PDL-Parallel-threads#6]
As identified on PDLPorters/pdl#385, a recent change in PDL (calling `SvOBJECT_off` on the ndarray's referencing `sv` member) has caused a big slowdown on finishing calculations.

"dave_the_m" on PerlMonks (https://perlmonks.org/?node_id=11141705) speculates as follows:

> When a thread is created, the whole active interpreter at that point is cloned (copied) into the new thread. When a thread ends, whatever SVs it returns (either explicitly via return, or implicitly as the last statement, or for XS, whatever SVs it pushes into the stack) are cloned back into the parent thread, by the parent calling the join() method. If the return SVs are non-trivial (e.g. have been blessed into a package), then additional stuff needs to be cloned back. For example if the object is in class X and the 'X' package doesn't exist in the parent (say 'use X' was done in the child, not the parent), then the X package and all the methods in that namespace need copying back too.
>
> What you are seeing is probably a situation where a large 'reverse clone' is being triggered by one of the SVs being returned to the parent. One possibility related to objects is the SVphv_CLONEABLE flag, which if set on the stash the object has been blessed into, triggers reverse-cloning the stash of that object.
>
> One possible side effect of turning off SvOBJECT() on the object is that it causes the SVphv_CLONEABLE test to be skipped (that test is only done on objects) which somehow causes the the stash associated with the (now unblessed) object to be cloned.
>
> But that's just wild speculation at the moment.

**Comment by marioroy** [comment]
I factored out PDL::Parallel::threads by adding "use threads" at the top of strassen_07_f.pl (using PDL::IO::FastRaw) and observe the same issue. Can you try a possible solution on the web? See [post](https://perlmonks.com/?node_id=11141726) on PerlMonks.

**Comment by mohawk2** [comment]
@marioroy reports that https://github.com/PDLPorters/pdl/commit/9369b8a3cb1dac0f27c45fa169458d4a8c2ddee3 in fact fixes the issue, so I will close this issue.
